/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FarmProduct: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            farmer_id: string;
            product_name: string;
            quantity: number;
            unit: string;
            harvest_date?: string;
            storage_location?: string;
            category?: string;
            price?: number;
            /** @enum {string} */
            status?: "available" | "sold" | "hidden";
            created_at?: string;
            updated_at?: string;
            spoilage_reason?: string;
        };
        MarketPrice: {
            /** Format: uuid */
            id?: string;
            product_name: string;
            category: string;
            unit: string;
            wholesale_price?: number | null;
            retail_price?: number | null;
            broker_price?: number | null;
            farmgate_price?: number | null;
            region?: string | null;
            source?: string | null;
            /** Format: date-time */
            collected_at?: string | null;
            /** @default false */
            benchmark: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
