/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FarmProduct: {
            /** Format: uuid */
            id?: string;
            farmer_id: number;
            product_name: string;
            quantity: number;
            unit: string;
            harvest_date?: string;
            storage_location?: string;
            category?: string;
            price?: number;
            /** @enum {string} */
            status?: "available" | "sold" | "hidden";
            created_at?: string;
            updated_at?: string;
            spoilage_reason?: string;
        };
        MarketPrice: {
            /** Format: uuid */
            id?: string;
            product_name: string;
            category: string;
            unit: string;
            wholesale_price?: number | null;
            retail_price?: number | null;
            broker_price?: number | null;
            farmgate_price?: number | null;
            region?: string | null;
            source?: string | null;
            /**
             * @default stable
             * @enum {string}
             */
            volatility: "stable" | "volatile";
            /** Format: date-time */
            collected_at?: string | null;
            /** @default false */
            benchmark: boolean;
            /** Format: date-time */
            last_synced?: string | null;
        };
        MarketplaceProduct: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            farm_product_id: string;
            farmer_id: string;
            product_name: string;
            quantity: number;
            unit: string;
            price: number;
            category?: string;
            /**
             * @default available
             * @enum {string}
             */
            status: "available" | "sold" | "reserved" | "hidden";
            location?: string;
            /** @default 0 */
            rating: number;
            /** @default 0 */
            total_sales: number;
            created_at?: string;
            updated_at?: string;
        };
        PublishToMarketplace: {
            /** Format: uuid */
            farm_product_id: string;
            price: number;
            /** @default true */
            is_public: boolean;
        };
        AddToCart: {
            /** Format: uuid */
            marketplace_product_id: string;
            quantity: number;
        };
        Checkout: {
            /** Format: uuid */
            cart_id: string;
            shipping_address?: string;
            /**
             * @default wallet
             * @enum {string}
             */
            payment_method: "wallet" | "mpesa" | "paybill" | "cash";
            notes?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
